# Generated by Django 5.1.4 on 2026-09-25 12:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0002_tenant_orgunit_identityprovider_membership'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capability',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('is_system', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='identity.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoleGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('principal_type', models.CharField(default='person', max_length=16)),
                ('principal_id', models.UUIDField()),
                ('scope_type', models.CharField(blank=True, default='', max_length=32)),
                ('scope_id', models.UUIDField(blank=True, null=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='authz.role')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='identity.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoleCapability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='authz.capability')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capabilities', to='authz.role')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='identity.tenant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('role', 'capability'), name='uniq_role_capability')],
            },
        ),
    ]
