# Generated by Django 5.1.4 on 2026-10-01 03:07

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0002_tenant_orgunit_identityprovider_membership'),
        ('skills', '0004_skillassertion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='identity.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JobProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade', models.SmallIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('published', 'published'), ('retired', 'retired')], default='draft', max_length=16)),
                ('version', models.SmallIntegerField(default=1)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='identity.tenant')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_profiles', to='profiles.track')),
            ],
            options={
                'ordering': ['track', 'grade', 'version'],
            },
        ),
        migrations.CreateModel(
            name='ProfileRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('min_level', models.SmallIntegerField()),
                ('criticality', models.CharField(choices=[('core', 'core'), ('supporting', 'supporting'), ('optional', 'optional')], max_length=16)),
                ('job_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='profiles.jobprofile')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='skills.skill')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='identity.tenant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('job_profile', 'skill'), name='uniq_profile_requirement_profile_skill')],
            },
        ),
        migrations.CreateModel(
            name='ReadinessSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('met', models.SmallIntegerField(default=0)),
                ('total', models.SmallIntegerField(default=0)),
                ('blocking_skill_ids', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), blank=True, default=list, size=None)),
                ('job_profile_version', models.SmallIntegerField()),
                ('computed_at', models.DateTimeField()),
                ('job_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='readiness_snapshots', to='profiles.jobprofile')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readiness_snapshots', to='identity.membership')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='identity.tenant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('membership', 'job_profile'), name='uniq_readiness_snapshot_membership_profile')],
            },
        ),
    ]
