# Generated by Django 5.1.4 on 2026-10-01 02:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0002_tenant_orgunit_identityprovider_membership'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillDomain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('sort', models.SmallIntegerField(default=0)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='identity.tenant')),
            ],
            options={
                'ordering': ['sort', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('external_code', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'draft'), ('published', 'published'), ('retired', 'retired')], default='draft', max_length=16)),
                ('version', models.SmallIntegerField(default=1)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='identity.tenant')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skills', to='skills.skilldomain')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SelfDeclaredSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.SmallIntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_declared_skills', to='identity.membership')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='identity.tenant')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='skills.skill')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('membership', 'skill'), name='uniq_self_declared_membership_skill')],
            },
        ),
        migrations.AddConstraint(
            model_name='skill',
            constraint=models.UniqueConstraint(fields=('tenant', 'slug', 'version'), name='uniq_skill_tenant_slug_version'),
        ),
    ]
