# Generated by Django 5.1.4 on 2026-10-01 03:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_tenant_orgunit_identityprovider_membership'),
        ('skills', '0002_skilledge_skilllevel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantSkillOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(blank=True, default='', max_length=16)),
                ('hidden', models.BooleanField(default=False)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='skills.skill')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='identity.tenant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant', 'skill'), name='uniq_tenant_skill_override')],
            },
        ),
    ]
