# Generated by Django 5.1.4 on 2026-10-01 02:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('identity', '0002_tenant_orgunit_identityprovider_membership'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=512)),
                ('response_status', models.PositiveSmallIntegerField()),
                ('response_body', models.JSONField(blank=True, default=dict)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='identity.tenant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant', 'key', 'method', 'path'), name='uniq_idempotency_tenant_key_method_path')],
            },
        ),
    ]
