# Generated by Django 5.1.4 on 2026-10-01 20:35

from django.db import migrations, models

# These partial unique indexes were created by identity.0004_invitation, which is
# already applied on this database. That file is no longer in the graph, so this
# migration still has to record the constraints in state without creating them twice.


def _index_exists(schema_editor, name: str) -> bool:
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT 1
            FROM pg_indexes
            WHERE tablename = 'identity_invitation' AND indexname = %s
            """,
            [name],
        )
        return cursor.fetchone() is not None


def _add_constraint(apps, schema_editor, constraint):
    if _index_exists(schema_editor, constraint.name):
        return
    invitation = apps.get_model("identity", "Invitation")
    schema_editor.add_constraint(invitation, constraint)


def _remove_constraint(apps, schema_editor, constraint):
    if not _index_exists(schema_editor, constraint.name):
        return
    invitation = apps.get_model("identity", "Invitation")
    schema_editor.remove_constraint(invitation, constraint)


def add_pending_email_constraint(apps, schema_editor):
    _add_constraint(
        apps,
        schema_editor,
        models.UniqueConstraint(
            condition=models.Q(status="pending"),
            fields=("tenant", "email"),
            name="uniq_pending_invitation_tenant_email",
        ),
    )


def remove_pending_email_constraint(apps, schema_editor):
    _remove_constraint(
        apps,
        schema_editor,
        models.UniqueConstraint(
            condition=models.Q(status="pending"),
            fields=("tenant", "email"),
            name="uniq_pending_invitation_tenant_email",
        ),
    )


def add_onboarding_hash_constraint(apps, schema_editor):
    _add_constraint(
        apps,
        schema_editor,
        models.UniqueConstraint(
            condition=~models.Q(onboarding_token_hash=""),
            fields=("onboarding_token_hash",),
            name="uniq_invitation_onboarding_token_hash",
        ),
    )


def remove_onboarding_hash_constraint(apps, schema_editor):
    _remove_constraint(
        apps,
        schema_editor,
        models.UniqueConstraint(
            condition=~models.Q(onboarding_token_hash=""),
            fields=("onboarding_token_hash",),
            name="uniq_invitation_onboarding_token_hash",
        ),
    )


class Migration(migrations.Migration):

    dependencies = [
        ("authz", "0001_initial"),
        ("identity", "0004_tenant_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitation",
            name="onboarding_token_hash",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=16,
            ),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddConstraint(
                    model_name="invitation",
                    constraint=models.UniqueConstraint(
                        condition=models.Q(("status", "pending")),
                        fields=("tenant", "email"),
                        name="uniq_pending_invitation_tenant_email",
                    ),
                ),
            ],
            database_operations=[
                migrations.RunPython(add_pending_email_constraint, remove_pending_email_constraint),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddConstraint(
                    model_name="invitation",
                    constraint=models.UniqueConstraint(
                        condition=models.Q(("onboarding_token_hash", ""), _negated=True),
                        fields=("onboarding_token_hash",),
                        name="uniq_invitation_onboarding_token_hash",
                    ),
                ),
            ],
            database_operations=[
                migrations.RunPython(
                    add_onboarding_hash_constraint, remove_onboarding_hash_constraint
                ),
            ],
        ),
    ]
